<a href="https://colab.research.google.com/github/zizobasry-cell/ischool-data-science/blob/main/data_frame.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
data = {
    "name" : ["ahmed" , "zein" , "mohamed" , "youssef" , "mariam" , "yehya"],
    "age"  :[50 , 17 , 30 , 18 , 25 , 15],
    "city" :["alex" , "fayoum" , "cairo" , "giza" , "alex" , "sharm elsheikh"],
    "py.score" : [88.0 , 85.0 , 90.0 , 70.0 , 90.0 , 95.0]
}
row_label=[101 , 102 , 103 , 104 , 105 , 106 ]

In [2]:
import pandas as pd

In [3]:
df = pd.DataFrame (data=data , index=row_label)

In [4]:
df

        name  age            city  py.score
101    ahmed   50            alex      88.0
102     zein   17          fayoum      85.0
103  mohamed   30           cairo      90.0
104  youssef   18            giza      70.0
105   mariam   25            alex      90.0
106    yehya   15  sharm elsheikh      95.0

In [5]:
df.to_csv("data.csv")

In [6]:
df = pd.read_csv("data.csv", index_col=0)

In [7]:
f1=df['py.score']>70
f2=df['age']<35

In [9]:
df.where(f1&f2 , inplace = True)
df

        name   age            city  py.score
101      NaN   NaN             NaN       NaN
102     zein  17.0          fayoum      85.0
103  mohamed  30.0           cairo      90.0
104      NaN   NaN             NaN       NaN
105   mariam  25.0            alex      90.0
106    yehya  15.0  sharm elsheikh      95.0